//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayagramsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Achievements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Achievements() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapayagramsClient.Properties.Achievements", typeof(Achievements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have 10 friends.
        /// </summary>
        internal static string add10Friends {
            get {
                return ResourceManager.GetString("add10Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have a friend.
        /// </summary>
        internal static string addFriend {
            get {
                return ResourceManager.GetString("addFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish 100 games.
        /// </summary>
        internal static string finish100Games {
            get {
                return ResourceManager.GetString("finish100Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish 10 games.
        /// </summary>
        internal static string finish10Games {
            get {
                return ResourceManager.GetString("finish10Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish 20 games.
        /// </summary>
        internal static string finish20Games {
            get {
                return ResourceManager.GetString("finish20Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish 5 games.
        /// </summary>
        internal static string finish5Games {
            get {
                return ResourceManager.GetString("finish5Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish your first game.
        /// </summary>
        internal static string finishGame {
            get {
                return ResourceManager.GetString("finishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Win 10 games.
        /// </summary>
        internal static string win10Games {
            get {
                return ResourceManager.GetString("win10Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Win a game.
        /// </summary>
        internal static string winGame {
            get {
                return ResourceManager.GetString("winGame", resourceCulture);
            }
        }
    }
}
