//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayagramsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapayagramsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string changePasswordCurrent {
            get {
                return ResourceManager.GetString("changePasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string changePasswordNew {
            get {
                return ResourceManager.GetString("changePasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string changePasswordNewConfirm {
            get {
                return ResourceManager.GetString("changePasswordNewConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a pin to your email.
        /// </summary>
        public static string changePasswordPinMessage {
            get {
                return ResourceManager.GetString("changePasswordPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string changePasswordSave {
            get {
                return ResourceManager.GetString("changePasswordSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string changePasswordTitle {
            get {
                return ResourceManager.GetString("changePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create papaya.
        /// </summary>
        public static string createGameCreate {
            get {
                return ResourceManager.GetString("createGameCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode.
        /// </summary>
        public static string createGameGameMode {
            get {
                return ResourceManager.GetString("createGameGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Words language.
        /// </summary>
        public static string createGameLanguage {
            get {
                return ResourceManager.GetString("createGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max players.
        /// </summary>
        public static string createGameMaxPlayers {
            get {
                return ResourceManager.GetString("createGameMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial pieces.
        /// </summary>
        public static string createGamePieces {
            get {
                return ResourceManager.GetString("createGamePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time limit.
        /// </summary>
        public static string createGameTimeLimit {
            get {
                return ResourceManager.GetString("createGameTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string createGameTitle {
            get {
                return ResourceManager.GetString("createGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while connecting.
        /// </summary>
        public static string errorConnectionTitle {
            get {
                return ResourceManager.GetString("errorConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to Papayagrams services, try again later..
        /// </summary>
        public static string errorDatabaseConnection {
            get {
                return ResourceManager.GetString("errorDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to server.
        /// </summary>
        public static string errorServerConnection {
            get {
                return ResourceManager.GetString("errorServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string gameInvitationAccept {
            get {
                return ResourceManager.GetString("gameInvitationAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is inviting you to a game.
        /// </summary>
        public static string gameInvitationMessage {
            get {
                return ResourceManager.GetString("gameInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string gameInvitationReject {
            get {
                return ResourceManager.GetString("gameInvitationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasic.
        /// </summary>
        public static string gameModeClasic {
            get {
                return ResourceManager.GetString("gameModeClasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death.
        /// </summary>
        public static string gameModeSuddenDeath {
            get {
                return ResourceManager.GetString("gameModeSuddenDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack.
        /// </summary>
        public static string gameModeTimeAttack {
            get {
                return ResourceManager.GetString("gameModeTimeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email cannot be left empty.
        /// </summary>
        public static string globalEmptyEmail {
            get {
                return ResourceManager.GetString("globalEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username cannot be empty.
        /// </summary>
        public static string globalEmptyUsername {
            get {
                return ResourceManager.GetString("globalEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaderboard.
        /// </summary>
        public static string globalLeaderboard {
            get {
                return ResourceManager.GetString("globalLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string joinGameCode {
            get {
                return ResourceManager.GetString("joinGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string joinGameJoin {
            get {
                return ResourceManager.GetString("joinGameJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string joinGameTitle {
            get {
                return ResourceManager.GetString("joinGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong code, try again.
        /// </summary>
        public static string joinGameWrongCode {
            get {
                return ResourceManager.GetString("joinGameWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        public static string mainMenuAchievements {
            get {
                return ResourceManager.GetString("mainMenuAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string mainMenuCreateGame {
            get {
                return ResourceManager.GetString("mainMenuCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string mainMenuJoinGame {
            get {
                return ResourceManager.GetString("mainMenuJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string mainMenuProfile {
            get {
                return ResourceManager.GetString("mainMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign out.
        /// </summary>
        public static string mainMenuSignOut {
            get {
                return ResourceManager.GetString("mainMenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string profileGamesWon {
            get {
                return ResourceManager.GetString("profileGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of friends.
        /// </summary>
        public static string profileNumberFriends {
            get {
                return ResourceManager.GetString("profileNumberFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original games played.
        /// </summary>
        public static string profileOriginalGames {
            get {
                return ResourceManager.GetString("profileOriginalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original games won.
        /// </summary>
        public static string profileOriginalGamesWon {
            get {
                return ResourceManager.GetString("profileOriginalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Played games.
        /// </summary>
        public static string profilePlayedGames {
            get {
                return ResourceManager.GetString("profilePlayedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string profileStatsTitle {
            get {
                return ResourceManager.GetString("profileStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death games played.
        /// </summary>
        public static string profileSuddenDeathGames {
            get {
                return ResourceManager.GetString("profileSuddenDeathGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death games won.
        /// </summary>
        public static string profileSuddenDeathGamesWon {
            get {
                return ResourceManager.GetString("profileSuddenDeathGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack games played.
        /// </summary>
        public static string profileTimeAttackGames {
            get {
                return ResourceManager.GetString("profileTimeAttackGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack games won.
        /// </summary>
        public static string profileTimeAttackGamesWon {
            get {
                return ResourceManager.GetString("profileTimeAttackGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My profile.
        /// </summary>
        public static string profileTitle {
            get {
                return ResourceManager.GetString("profileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account? Sign in.
        /// </summary>
        public static string registerAlreadyRegistered {
            get {
                return ResourceManager.GetString("registerAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already an account linked to this email.
        /// </summary>
        public static string registerEmailAlreadyLinked {
            get {
                return ResourceManager.GetString("registerEmailAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username already exists.
        /// </summary>
        public static string registerExistingUsername {
            get {
                return ResourceManager.GetString("registerExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        public static string registerInvalidEmail {
            get {
                return ResourceManager.GetString("registerInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string registerSignUp {
            get {
                return ResourceManager.GetString("registerSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account was created successfully, you can now log in.
        /// </summary>
        public static string registerSuccessful {
            get {
                return ResourceManager.GetString("registerSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registered.
        /// </summary>
        public static string registerSuccessfulTitle {
            get {
                return ResourceManager.GetString("registerSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string registerTitle {
            get {
                return ResourceManager.GetString("registerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weak password.
        /// </summary>
        public static string registerWeakPassword {
            get {
                return ResourceManager.GetString("registerWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password cannot be empty.
        /// </summary>
        public static string signInEmptyPassword {
            get {
                return ResourceManager.GetString("signInEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string signInForgotPassword {
            get {
                return ResourceManager.GetString("signInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game as guest.
        /// </summary>
        public static string signInJoinAsGuest {
            get {
                return ResourceManager.GetString("signInJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string signInSignUp {
            get {
                return ResourceManager.GetString("signInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong username or password.
        /// </summary>
        public static string signInWrongCredentials {
            get {
                return ResourceManager.GetString("signInWrongCredentials", resourceCulture);
            }
        }
    }
}
