//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayagramsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapayagramsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        internal static string changePasswordCurrent {
            get {
                return ResourceManager.GetString("changePasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        internal static string changePasswordNew {
            get {
                return ResourceManager.GetString("changePasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string changePasswordNewConfirm {
            get {
                return ResourceManager.GetString("changePasswordNewConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a pin to your email.
        /// </summary>
        internal static string changePasswordPinMessage {
            get {
                return ResourceManager.GetString("changePasswordPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string changePasswordSave {
            get {
                return ResourceManager.GetString("changePasswordSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        internal static string changePasswordTitle {
            get {
                return ResourceManager.GetString("changePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create papaya.
        /// </summary>
        internal static string createGameCreate {
            get {
                return ResourceManager.GetString("createGameCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode.
        /// </summary>
        internal static string createGameGameMode {
            get {
                return ResourceManager.GetString("createGameGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Words language.
        /// </summary>
        internal static string createGameLanguage {
            get {
                return ResourceManager.GetString("createGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max players.
        /// </summary>
        internal static string createGameMaxPlayers {
            get {
                return ResourceManager.GetString("createGameMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial pieces.
        /// </summary>
        internal static string createGamePieces {
            get {
                return ResourceManager.GetString("createGamePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time limit.
        /// </summary>
        internal static string createGameTimeLimit {
            get {
                return ResourceManager.GetString("createGameTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        internal static string createGameTitle {
            get {
                return ResourceManager.GetString("createGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string gameInvitationAccept {
            get {
                return ResourceManager.GetString("gameInvitationAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is inviting you to a game.
        /// </summary>
        internal static string gameInvitationMessage {
            get {
                return ResourceManager.GetString("gameInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        internal static string gameInvitationReject {
            get {
                return ResourceManager.GetString("gameInvitationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasic.
        /// </summary>
        internal static string gameModeClasic {
            get {
                return ResourceManager.GetString("gameModeClasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death.
        /// </summary>
        internal static string gameModeSuddenDeath {
            get {
                return ResourceManager.GetString("gameModeSuddenDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack.
        /// </summary>
        internal static string gameModeTimeAttack {
            get {
                return ResourceManager.GetString("gameModeTimeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        internal static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        internal static string joinGameCode {
            get {
                return ResourceManager.GetString("joinGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        internal static string joinGameJoin {
            get {
                return ResourceManager.GetString("joinGameJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        internal static string joinGameTitle {
            get {
                return ResourceManager.GetString("joinGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong code, try again.
        /// </summary>
        internal static string joinGameWrongCode {
            get {
                return ResourceManager.GetString("joinGameWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        internal static string mainMenuAchievements {
            get {
                return ResourceManager.GetString("mainMenuAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        internal static string mainMenuCreateGame {
            get {
                return ResourceManager.GetString("mainMenuCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        internal static string mainMenuJoinGame {
            get {
                return ResourceManager.GetString("mainMenuJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string mainMenuProfile {
            get {
                return ResourceManager.GetString("mainMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign out.
        /// </summary>
        internal static string mainMenuSignOut {
            get {
                return ResourceManager.GetString("mainMenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account? Sign in.
        /// </summary>
        internal static string registerAlreadyRegistered {
            get {
                return ResourceManager.GetString("registerAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already an account linked to this email.
        /// </summary>
        internal static string registerEmailAlreadyLinked {
            get {
                return ResourceManager.GetString("registerEmailAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username already exists.
        /// </summary>
        internal static string registerExistingUsername {
            get {
                return ResourceManager.GetString("registerExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        internal static string registerInvalidEmail {
            get {
                return ResourceManager.GetString("registerInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string registerSignUp {
            get {
                return ResourceManager.GetString("registerSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weak password.
        /// </summary>
        internal static string registerWeakPassword {
            get {
                return ResourceManager.GetString("registerWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        internal static string signInForgotPassword {
            get {
                return ResourceManager.GetString("signInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game as guest.
        /// </summary>
        internal static string signInJoinAsGuest {
            get {
                return ResourceManager.GetString("signInJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string signInSignUp {
            get {
                return ResourceManager.GetString("signInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong username.
        /// </summary>
        internal static string signInWrongUsername {
            get {
                return ResourceManager.GetString("signInWrongUsername", resourceCulture);
            }
        }
    }
}
