//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayagramsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapayagramsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string changePasswordCurrent {
            get {
                return ResourceManager.GetString("changePasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string changePasswordNew {
            get {
                return ResourceManager.GetString("changePasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string changePasswordNewConfirm {
            get {
                return ResourceManager.GetString("changePasswordNewConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a pin to your email.
        /// </summary>
        public static string changePasswordPinMessage {
            get {
                return ResourceManager.GetString("changePasswordPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string changePasswordSave {
            get {
                return ResourceManager.GetString("changePasswordSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string changePasswordTitle {
            get {
                return ResourceManager.GetString("changePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursor.
        /// </summary>
        public static string configurationCursor {
            get {
                return ResourceManager.GetString("configurationCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App language.
        /// </summary>
        public static string configurationLanguage {
            get {
                return ResourceManager.GetString("configurationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piece color.
        /// </summary>
        public static string configurationPieceColor {
            get {
                return ResourceManager.GetString("configurationPieceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Same as system.
        /// </summary>
        public static string configurationSystemLanguage {
            get {
                return ResourceManager.GetString("configurationSystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic.
        /// </summary>
        public static string createGameClassicMode {
            get {
                return ResourceManager.GetString("createGameClassicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create papaya.
        /// </summary>
        public static string createGameCreate {
            get {
                return ResourceManager.GetString("createGameCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string createGameEnglishLanguage {
            get {
                return ResourceManager.GetString("createGameEnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode.
        /// </summary>
        public static string createGameGameMode {
            get {
                return ResourceManager.GetString("createGameGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Words language.
        /// </summary>
        public static string createGameLanguage {
            get {
                return ResourceManager.GetString("createGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max players.
        /// </summary>
        public static string createGameMaxPlayers {
            get {
                return ResourceManager.GetString("createGameMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutes.
        /// </summary>
        public static string createGameMinutes {
            get {
                return ResourceManager.GetString("createGameMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No limit.
        /// </summary>
        public static string createGameNoTimeLimit {
            get {
                return ResourceManager.GetString("createGameNoTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial pieces.
        /// </summary>
        public static string createGamePieces {
            get {
                return ResourceManager.GetString("createGamePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string createGameSpanishLanguage {
            get {
                return ResourceManager.GetString("createGameSpanishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death.
        /// </summary>
        public static string createGameSuddenDeathMode {
            get {
                return ResourceManager.GetString("createGameSuddenDeathMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack.
        /// </summary>
        public static string createGameTimeAttackMode {
            get {
                return ResourceManager.GetString("createGameTimeAttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time limit.
        /// </summary>
        public static string createGameTimeLimit {
            get {
                return ResourceManager.GetString("createGameTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string createGameTitle {
            get {
                return ResourceManager.GetString("createGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic.
        /// </summary>
        public static string cursorClassic {
            get {
                return ResourceManager.GetString("cursorClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Papaya.
        /// </summary>
        public static string cursorPapaya {
            get {
                return ResourceManager.GetString("cursorPapaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while connecting.
        /// </summary>
        public static string errorConnectionTitle {
            get {
                return ResourceManager.GetString("errorConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t block player.
        /// </summary>
        public static string errorCouldntBlockPlayer {
            get {
                return ResourceManager.GetString("errorCouldntBlockPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t remove player from friends.
        /// </summary>
        public static string errorCouldntUnfriendPlayer {
            get {
                return ResourceManager.GetString("errorCouldntUnfriendPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to Papayagrams services, try again later..
        /// </summary>
        public static string errorDatabaseConnection {
            get {
                return ResourceManager.GetString("errorDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred.
        /// </summary>
        public static string errorOccurredTitle {
            get {
                return ResourceManager.GetString("errorOccurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to server.
        /// </summary>
        public static string errorServerConnection {
            get {
                return ResourceManager.GetString("errorServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred, try again and if the problem persiste, restart the game.
        /// </summary>
        public static string errorUnexpectedError {
            get {
                return ResourceManager.GetString("errorUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept request.
        /// </summary>
        public static string friendsAcceptRequestTooltip {
            get {
                return ResourceManager.GetString("friendsAcceptRequestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already friend of this user.
        /// </summary>
        public static string friendsAlreadyFriends {
            get {
                return ResourceManager.GetString("friendsAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a friend request to this player.
        /// </summary>
        public static string friendsAlreadyRequestedUser {
            get {
                return ResourceManager.GetString("friendsAlreadyRequestedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block user.
        /// </summary>
        public static string friendsBlockUserTooltip {
            get {
                return ResourceManager.GetString("friendsBlockUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have a friend request from the user, switch friend menu view with the top right button to see your requests.
        /// </summary>
        public static string friendsPendingRequestFromUser {
            get {
                return ResourceManager.GetString("friendsPendingRequestFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player blocked successfully.
        /// </summary>
        public static string friendsPlayerBlockedSuccessfully {
            get {
                return ResourceManager.GetString("friendsPlayerBlockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player unblocked successfully.
        /// </summary>
        public static string friendsPlayerUnblockedSuccessfully {
            get {
                return ResourceManager.GetString("friendsPlayerUnblockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject request.
        /// </summary>
        public static string friendsRejectRequestTooltip {
            get {
                return ResourceManager.GetString("friendsRejectRequestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove friend.
        /// </summary>
        public static string friendsRemoveFriendTooltip {
            get {
                return ResourceManager.GetString("friendsRemoveFriendTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request has been sent.
        /// </summary>
        public static string friendsRequestSent {
            get {
                return ResourceManager.GetString("friendsRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent.
        /// </summary>
        public static string friendsRequestSentTitle {
            get {
                return ResourceManager.GetString("friendsRequestSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switch view.
        /// </summary>
        public static string friendsSwitchView {
            get {
                return ResourceManager.GetString("friendsSwitchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string friendsTitle {
            get {
                return ResourceManager.GetString("friendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unblock user.
        /// </summary>
        public static string friendsUnblockUserTooltip {
            get {
                return ResourceManager.GetString("friendsUnblockUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is blocked.
        /// </summary>
        public static string friendsUserIsBlocked {
            get {
                return ResourceManager.GetString("friendsUserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculating results.
        /// </summary>
        public static string gameEndCalculating {
            get {
                return ResourceManager.GetString("gameEndCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game finished.
        /// </summary>
        public static string gameEndFinished {
            get {
                return ResourceManager.GetString("gameEndFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        public static string gameEndLeave {
            get {
                return ResourceManager.GetString("gameEndLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The winner is.
        /// </summary>
        public static string gameEndWinner {
            get {
                return ResourceManager.GetString("gameEndWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string gameInvitationAccept {
            get {
                return ResourceManager.GetString("gameInvitationAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is inviting you to a game.
        /// </summary>
        public static string gameInvitationMessage {
            get {
                return ResourceManager.GetString("gameInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string gameInvitationReject {
            get {
                return ResourceManager.GetString("gameInvitationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave?.
        /// </summary>
        public static string gameLeaveGame {
            get {
                return ResourceManager.GetString("gameLeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave game.
        /// </summary>
        public static string gameLeaveGameTitle {
            get {
                return ResourceManager.GetString("gameLeaveGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic.
        /// </summary>
        public static string gameModeClasic {
            get {
                return ResourceManager.GetString("gameModeClasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death.
        /// </summary>
        public static string gameModeSuddenDeath {
            get {
                return ResourceManager.GetString("gameModeSuddenDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack.
        /// </summary>
        public static string gameModeTimeAttack {
            get {
                return ResourceManager.GetString("gameModeTimeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string globalAccept {
            get {
                return ResourceManager.GetString("globalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked users.
        /// </summary>
        public static string globalBlockedUsers {
            get {
                return ResourceManager.GetString("globalBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string globalClose {
            get {
                return ResourceManager.GetString("globalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string globalConfiguration {
            get {
                return ResourceManager.GetString("globalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email cannot be left empty.
        /// </summary>
        public static string globalEmptyEmail {
            get {
                return ResourceManager.GetString("globalEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username cannot be empty.
        /// </summary>
        public static string globalEmptyUsername {
            get {
                return ResourceManager.GetString("globalEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string globalFriends {
            get {
                return ResourceManager.GetString("globalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaderboard.
        /// </summary>
        public static string globalLeaderboard {
            get {
                return ResourceManager.GetString("globalLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string globalNewPassword {
            get {
                return ResourceManager.GetString("globalNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat new password.
        /// </summary>
        public static string globalNewPasswordAgain {
            get {
                return ResourceManager.GetString("globalNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated successfully.
        /// </summary>
        public static string globalPasswordChanged {
            get {
                return ResourceManager.GetString("globalPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests.
        /// </summary>
        public static string globalRequests {
            get {
                return ResourceManager.GetString("globalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string globalSignIn {
            get {
                return ResourceManager.GetString("globalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game code is wrong or the lobby is full.
        /// </summary>
        public static string joinGameCantJoin {
            get {
                return ResourceManager.GetString("joinGameCantJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn´t connect to lobby.
        /// </summary>
        public static string joinGameCantJoinTitle {
            get {
                return ResourceManager.GetString("joinGameCantJoinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string joinGameCode {
            get {
                return ResourceManager.GetString("joinGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string joinGameJoin {
            get {
                return ResourceManager.GetString("joinGameJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string joinGameTitle {
            get {
                return ResourceManager.GetString("joinGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong code, try again.
        /// </summary>
        public static string joinGameWrongCode {
            get {
                return ResourceManager.GetString("joinGameWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent successfully.
        /// </summary>
        public static string lobbyFriendInvited {
            get {
                return ResourceManager.GetString("lobbyFriendInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No game room with that code exists.
        /// </summary>
        public static string lobbyRoomNotFound {
            get {
                return ResourceManager.GetString("lobbyRoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room not found.
        /// </summary>
        public static string lobbyRoomNotFoundTitle {
            get {
                return ResourceManager.GetString("lobbyRoomNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code we sent to your email.
        /// </summary>
        public static string loginVerificationCode {
            get {
                return ResourceManager.GetString("loginVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        public static string mainMenuAchievements {
            get {
                return ResourceManager.GetString("mainMenuAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string mainMenuCreateGame {
            get {
                return ResourceManager.GetString("mainMenuCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string mainMenuJoinGame {
            get {
                return ResourceManager.GetString("mainMenuJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string mainMenuProfile {
            get {
                return ResourceManager.GetString("mainMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign out.
        /// </summary>
        public static string mainMenuSignOut {
            get {
                return ResourceManager.GetString("mainMenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string profileGamesWon {
            get {
                return ResourceManager.GetString("profileGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of friends.
        /// </summary>
        public static string profileNumberFriends {
            get {
                return ResourceManager.GetString("profileNumberFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original games played.
        /// </summary>
        public static string profileOriginalGames {
            get {
                return ResourceManager.GetString("profileOriginalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original games won.
        /// </summary>
        public static string profileOriginalGamesWon {
            get {
                return ResourceManager.GetString("profileOriginalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Played games.
        /// </summary>
        public static string profilePlayedGames {
            get {
                return ResourceManager.GetString("profilePlayedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string profileStatsTitle {
            get {
                return ResourceManager.GetString("profileStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death games played: .
        /// </summary>
        public static string profileSuddenDeathGames {
            get {
                return ResourceManager.GetString("profileSuddenDeathGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sudden death games won: .
        /// </summary>
        public static string profileSuddenDeathGamesWon {
            get {
                return ResourceManager.GetString("profileSuddenDeathGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack games played: .
        /// </summary>
        public static string profileTimeAttackGames {
            get {
                return ResourceManager.GetString("profileTimeAttackGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time attack games won: .
        /// </summary>
        public static string profileTimeAttackGamesWon {
            get {
                return ResourceManager.GetString("profileTimeAttackGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My profile.
        /// </summary>
        public static string profileTitle {
            get {
                return ResourceManager.GetString("profileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords dont match.
        /// </summary>
        public static string recoverPasswordsDontMatch {
            get {
                return ResourceManager.GetString("recoverPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send recover code.
        /// </summary>
        public static string recoverSendCode {
            get {
                return ResourceManager.GetString("recoverSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string recoverTitle {
            get {
                return ResourceManager.GetString("recoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account? Sign in.
        /// </summary>
        public static string registerAlreadyRegistered {
            get {
                return ResourceManager.GetString("registerAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already an account linked to this email.
        /// </summary>
        public static string registerEmailAlreadyLinked {
            get {
                return ResourceManager.GetString("registerEmailAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username already exists.
        /// </summary>
        public static string registerExistingUsername {
            get {
                return ResourceManager.GetString("registerExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        public static string registerInvalidEmail {
            get {
                return ResourceManager.GetString("registerInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string registerSignUp {
            get {
                return ResourceManager.GetString("registerSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account was created successfully, you can now log in.
        /// </summary>
        public static string registerSuccessful {
            get {
                return ResourceManager.GetString("registerSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registered.
        /// </summary>
        public static string registerSuccessfulTitle {
            get {
                return ResourceManager.GetString("registerSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string registerTitle {
            get {
                return ResourceManager.GetString("registerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weak password.
        /// </summary>
        public static string registerWeakPassword {
            get {
                return ResourceManager.GetString("registerWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password cannot be empty.
        /// </summary>
        public static string signInEmptyPassword {
            get {
                return ResourceManager.GetString("signInEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string signInForgotPassword {
            get {
                return ResourceManager.GetString("signInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game as guest.
        /// </summary>
        public static string signInJoinAsGuest {
            get {
                return ResourceManager.GetString("signInJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string signInSignUp {
            get {
                return ResourceManager.GetString("signInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong username or password.
        /// </summary>
        public static string signInWrongCredentials {
            get {
                return ResourceManager.GetString("signInWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lost games.
        /// </summary>
        public static string statsGamesLost {
            get {
                return ResourceManager.GetString("statsGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We sent a code to your email.
        /// </summary>
        public static string verificationCode {
            get {
                return ResourceManager.GetString("verificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field cannot be empty.
        /// </summary>
        public static string verificationEmptyCode {
            get {
                return ResourceManager.GetString("verificationEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code again.
        /// </summary>
        public static string verificationResendMessage {
            get {
                return ResourceManager.GetString("verificationResendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong code, try again.
        /// </summary>
        public static string verificationWrongCode {
            get {
                return ResourceManager.GetString("verificationWrongCode", resourceCulture);
            }
        }
    }
}
