//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class papayagramsEntities : DbContext
    {
        public papayagramsEntities()
            : base("name=papayagramsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<OriginalGameHistory> OriginalGameHistory { get; set; }
        public virtual DbSet<SuddenDeathHistory> SuddenDeathHistory { get; set; }
        public virtual DbSet<TimeAtackHistory> TimeAtackHistory { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAchieved> UserAchieved { get; set; }
        public virtual DbSet<UserConfiguration> UserConfiguration { get; set; }
        public virtual DbSet<UserRelationship> UserRelationship { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
    }
}
