//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapayagramsClient.PapayagramsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class PlayerDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfileIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfileIcon {
            get {
                return this.ProfileIconField;
            }
            set {
                if ((this.ProfileIconField.Equals(value) != true)) {
                    this.ProfileIconField = value;
                    this.RaisePropertyChanged("ProfileIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class FriendDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.RelationStateDC RelationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.RelationStateDC RelationState {
            get {
                return this.RelationStateField;
            }
            set {
                if ((this.RelationStateField.Equals(value) != true)) {
                    this.RelationStateField = value;
                    this.RaisePropertyChanged("RelationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationStateDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public enum RelationStateDC : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatsDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class PlayerStatsDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendsAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OriginalGamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OriginalGamesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SuddenDeathGamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SuddenDeathGamesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeAttackGamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeAttackGamesWonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendsAmount {
            get {
                return this.FriendsAmountField;
            }
            set {
                if ((this.FriendsAmountField.Equals(value) != true)) {
                    this.FriendsAmountField = value;
                    this.RaisePropertyChanged("FriendsAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginalGamesPlayed {
            get {
                return this.OriginalGamesPlayedField;
            }
            set {
                if ((this.OriginalGamesPlayedField.Equals(value) != true)) {
                    this.OriginalGamesPlayedField = value;
                    this.RaisePropertyChanged("OriginalGamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginalGamesWon {
            get {
                return this.OriginalGamesWonField;
            }
            set {
                if ((this.OriginalGamesWonField.Equals(value) != true)) {
                    this.OriginalGamesWonField = value;
                    this.RaisePropertyChanged("OriginalGamesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuddenDeathGamesPlayed {
            get {
                return this.SuddenDeathGamesPlayedField;
            }
            set {
                if ((this.SuddenDeathGamesPlayedField.Equals(value) != true)) {
                    this.SuddenDeathGamesPlayedField = value;
                    this.RaisePropertyChanged("SuddenDeathGamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuddenDeathGamesWon {
            get {
                return this.SuddenDeathGamesWonField;
            }
            set {
                if ((this.SuddenDeathGamesWonField.Equals(value) != true)) {
                    this.SuddenDeathGamesWonField = value;
                    this.RaisePropertyChanged("SuddenDeathGamesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeAttackGamesPlayed {
            get {
                return this.TimeAttackGamesPlayedField;
            }
            set {
                if ((this.TimeAttackGamesPlayedField.Equals(value) != true)) {
                    this.TimeAttackGamesPlayedField = value;
                    this.RaisePropertyChanged("TimeAttackGamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeAttackGamesWon {
            get {
                return this.TimeAttackGamesWonField;
            }
            set {
                if ((this.TimeAttackGamesWonField.Equals(value) != true)) {
                    this.TimeAttackGamesWonField = value;
                    this.RaisePropertyChanged("TimeAttackGamesWon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AchievementDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class AchievementDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAchievedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAchieved {
            get {
                return this.IsAchievedField;
            }
            set {
                if ((this.IsAchievedField.Equals(value) != true)) {
                    this.IsAchievedField = value;
                    this.RaisePropertyChanged("IsAchieved");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaderboardStatsDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class LeaderboardStatsDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesLostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalGamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesLost {
            get {
                return this.GamesLostField;
            }
            set {
                if ((this.GamesLostField.Equals(value) != true)) {
                    this.GamesLostField = value;
                    this.RaisePropertyChanged("GamesLost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesWon {
            get {
                return this.GamesWonField;
            }
            set {
                if ((this.GamesWonField.Equals(value) != true)) {
                    this.GamesWonField = value;
                    this.RaisePropertyChanged("GamesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername {
            get {
                return this.PlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUsernameField, value) != true)) {
                    this.PlayerUsernameField = value;
                    this.RaisePropertyChanged("PlayerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalGames {
            get {
                return this.TotalGamesField;
            }
            set {
                if ((this.TotalGamesField.Equals(value) != true)) {
                    this.TotalGamesField = value;
                    this.RaisePropertyChanged("TotalGames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInvitationDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class GameInvitationDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameRoomCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameRoomCode {
            get {
                return this.GameRoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameRoomCodeField, value) != true)) {
                    this.GameRoomCodeField = value;
                    this.RaisePropertyChanged("GameRoomCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername {
            get {
                return this.SenderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUsernameField, value) != true)) {
                    this.SenderUsernameField = value;
                    this.RaisePropertyChanged("SenderUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationSettingsDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class ApplicationSettingsDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PieceColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.ApplicationLanguageDC SelectedLanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cursor {
            get {
                return this.CursorField;
            }
            set {
                if ((this.CursorField.Equals(value) != true)) {
                    this.CursorField = value;
                    this.RaisePropertyChanged("Cursor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PieceColor {
            get {
                return this.PieceColorField;
            }
            set {
                if ((this.PieceColorField.Equals(value) != true)) {
                    this.PieceColorField = value;
                    this.RaisePropertyChanged("PieceColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.ApplicationLanguageDC SelectedLanguage {
            get {
                return this.SelectedLanguageField;
            }
            set {
                if ((this.SelectedLanguageField.Equals(value) != true)) {
                    this.SelectedLanguageField = value;
                    this.RaisePropertyChanged("SelectedLanguage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationLanguageDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public enum ApplicationLanguageDC : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        english = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        spanish = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        auto = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameConfigurationDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class GameConfigurationDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.GameModeDC GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InitialPiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeLimitMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.LanguageDC WordsLanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.GameModeDC GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((this.GameModeField.Equals(value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InitialPieces {
            get {
                return this.InitialPiecesField;
            }
            set {
                if ((this.InitialPiecesField.Equals(value) != true)) {
                    this.InitialPiecesField = value;
                    this.RaisePropertyChanged("InitialPieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeLimitMinutes {
            get {
                return this.TimeLimitMinutesField;
            }
            set {
                if ((this.TimeLimitMinutesField.Equals(value) != true)) {
                    this.TimeLimitMinutesField = value;
                    this.RaisePropertyChanged("TimeLimitMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.LanguageDC WordsLanguage {
            get {
                return this.WordsLanguageField;
            }
            set {
                if ((this.WordsLanguageField.Equals(value) != true)) {
                    this.WordsLanguageField = value;
                    this.RaisePropertyChanged("WordsLanguage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameModeDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public enum GameModeDC : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Original = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuddenDeath = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeAttack = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    public enum LanguageDC : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameRoomDC", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class GameRoomDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.GameConfigurationDC GameConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PapayagramsClient.PapayagramsService.PlayerDC[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.GameConfigurationDC GameConfiguration {
            get {
                return this.GameConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.GameConfigurationField, value) != true)) {
                    this.GameConfigurationField = value;
                    this.RaisePropertyChanged("GameConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PapayagramsClient.PapayagramsService.PlayerDC[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode {
            get {
                return this.RoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCodeField, value) != true)) {
                    this.RoomCodeField = value;
                    this.RaisePropertyChanged("RoomCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameRoomCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorUsername {
            get {
                return this.AuthorUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorUsernameField, value) != true)) {
                    this.AuthorUsernameField = value;
                    this.RaisePropertyChanged("AuthorUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameRoomCode {
            get {
                return this.GameRoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameRoomCodeField, value) != true)) {
                    this.GameRoomCodeField = value;
                    this.RaisePropertyChanged("GameRoomCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RegisterUser", ReplyAction="http://tempuri.org/ILoginService/RegisterUserResponse")]
        int RegisterUser(PapayagramsClient.PapayagramsService.PlayerDC player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RegisterUser", ReplyAction="http://tempuri.org/ILoginService/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(PapayagramsClient.PapayagramsService.PlayerDC player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Login", ReplyAction="http://tempuri.org/ILoginService/LoginResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC> Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Login", ReplyAction="http://tempuri.org/ILoginService/LoginResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC>> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Logout", ReplyAction="http://tempuri.org/ILoginService/LogoutResponse")]
        int Logout(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Logout", ReplyAction="http://tempuri.org/ILoginService/LogoutResponse")]
        System.Threading.Tasks.Task<int> LogoutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/VerifyAccount", ReplyAction="http://tempuri.org/ILoginService/VerifyAccountResponse")]
        int VerifyAccount(string username, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/VerifyAccount", ReplyAction="http://tempuri.org/ILoginService/VerifyAccountResponse")]
        System.Threading.Tasks.Task<int> VerifyAccountAsync(string username, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SendAccountVerificationCode", ReplyAction="http://tempuri.org/ILoginService/SendAccountVerificationCodeResponse")]
        int SendAccountVerificationCode(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SendAccountVerificationCode", ReplyAction="http://tempuri.org/ILoginService/SendAccountVerificationCodeResponse")]
        System.Threading.Tasks.Task<int> SendAccountVerificationCodeAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AccessAsGuest", ReplyAction="http://tempuri.org/ILoginService/AccessAsGuestResponse")]
        PapayagramsClient.PapayagramsService.PlayerDC AccessAsGuest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AccessAsGuest", ReplyAction="http://tempuri.org/ILoginService/AccessAsGuestResponse")]
        System.Threading.Tasks.Task<PapayagramsClient.PapayagramsService.PlayerDC> AccessAsGuestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SendPasswordRecoveryPIN", ReplyAction="http://tempuri.org/ILoginService/SendPasswordRecoveryPINResponse")]
        int SendPasswordRecoveryPIN(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SendPasswordRecoveryPIN", ReplyAction="http://tempuri.org/ILoginService/SendPasswordRecoveryPINResponse")]
        System.Threading.Tasks.Task<int> SendPasswordRecoveryPINAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RecoverPassword", ReplyAction="http://tempuri.org/ILoginService/RecoverPasswordResponse")]
        int RecoverPassword(string pin, string email, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RecoverPassword", ReplyAction="http://tempuri.org/ILoginService/RecoverPasswordResponse")]
        System.Threading.Tasks.Task<int> RecoverPasswordAsync(string pin, string email, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : PapayagramsClient.PapayagramsService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<PapayagramsClient.PapayagramsService.ILoginService>, PapayagramsClient.PapayagramsService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegisterUser(PapayagramsClient.PapayagramsService.PlayerDC player) {
            return base.Channel.RegisterUser(player);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(PapayagramsClient.PapayagramsService.PlayerDC player) {
            return base.Channel.RegisterUserAsync(player);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC> Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC>> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public int Logout(string username) {
            return base.Channel.Logout(username);
        }
        
        public System.Threading.Tasks.Task<int> LogoutAsync(string username) {
            return base.Channel.LogoutAsync(username);
        }
        
        public int VerifyAccount(string username, string code) {
            return base.Channel.VerifyAccount(username, code);
        }
        
        public System.Threading.Tasks.Task<int> VerifyAccountAsync(string username, string code) {
            return base.Channel.VerifyAccountAsync(username, code);
        }
        
        public int SendAccountVerificationCode(string username) {
            return base.Channel.SendAccountVerificationCode(username);
        }
        
        public System.Threading.Tasks.Task<int> SendAccountVerificationCodeAsync(string username) {
            return base.Channel.SendAccountVerificationCodeAsync(username);
        }
        
        public PapayagramsClient.PapayagramsService.PlayerDC AccessAsGuest() {
            return base.Channel.AccessAsGuest();
        }
        
        public System.Threading.Tasks.Task<PapayagramsClient.PapayagramsService.PlayerDC> AccessAsGuestAsync() {
            return base.Channel.AccessAsGuestAsync();
        }
        
        public int SendPasswordRecoveryPIN(string email) {
            return base.Channel.SendPasswordRecoveryPIN(email);
        }
        
        public System.Threading.Tasks.Task<int> SendPasswordRecoveryPINAsync(string email) {
            return base.Channel.SendPasswordRecoveryPINAsync(email);
        }
        
        public int RecoverPassword(string pin, string email, string newPassword) {
            return base.Channel.RecoverPassword(pin, email, newPassword);
        }
        
        public System.Threading.Tasks.Task<int> RecoverPasswordAsync(string pin, string email, string newPassword) {
            return base.Channel.RecoverPasswordAsync(pin, email, newPassword);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.IMainMenuService", CallbackContract=typeof(PapayagramsClient.PapayagramsService.IMainMenuServiceCallback))]
    public interface IMainMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetAllRelationships", ReplyAction="http://tempuri.org/IMainMenuService/GetAllRelationshipsResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.FriendDC[]> GetAllRelationships(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetAllRelationships", ReplyAction="http://tempuri.org/IMainMenuService/GetAllRelationshipsResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.FriendDC[]>> GetAllRelationshipsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/SearchNoFriendPlayer", ReplyAction="http://tempuri.org/IMainMenuService/SearchNoFriendPlayerResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC> SearchNoFriendPlayer(string searcherUsername, string searchedUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/SearchNoFriendPlayer", ReplyAction="http://tempuri.org/IMainMenuService/SearchNoFriendPlayerResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC>> SearchNoFriendPlayerAsync(string searcherUsername, string searchedUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/SendFriendRequest", ReplyAction="http://tempuri.org/IMainMenuService/SendFriendRequestResponse")]
        int SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/SendFriendRequest", ReplyAction="http://tempuri.org/IMainMenuService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<int> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/RespondFriendRequest", ReplyAction="http://tempuri.org/IMainMenuService/RespondFriendRequestResponse")]
        int RespondFriendRequest(string respondentUsername, string requesterUsername, bool response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/RespondFriendRequest", ReplyAction="http://tempuri.org/IMainMenuService/RespondFriendRequestResponse")]
        System.Threading.Tasks.Task<int> RespondFriendRequestAsync(string respondentUsername, string requesterUsername, bool response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/RemoveFriend", ReplyAction="http://tempuri.org/IMainMenuService/RemoveFriendResponse")]
        int RemoveFriend(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/RemoveFriend", ReplyAction="http://tempuri.org/IMainMenuService/RemoveFriendResponse")]
        System.Threading.Tasks.Task<int> RemoveFriendAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/BlockPlayer", ReplyAction="http://tempuri.org/IMainMenuService/BlockPlayerResponse")]
        int BlockPlayer(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/BlockPlayer", ReplyAction="http://tempuri.org/IMainMenuService/BlockPlayerResponse")]
        System.Threading.Tasks.Task<int> BlockPlayerAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/UnblockPlayer", ReplyAction="http://tempuri.org/IMainMenuService/UnblockPlayerResponse")]
        int UnblockPlayer(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/UnblockPlayer", ReplyAction="http://tempuri.org/IMainMenuService/UnblockPlayerResponse")]
        System.Threading.Tasks.Task<int> UnblockPlayerAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetPlayerProfile", ReplyAction="http://tempuri.org/IMainMenuService/GetPlayerProfileResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerStatsDC> GetPlayerProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetPlayerProfile", ReplyAction="http://tempuri.org/IMainMenuService/GetPlayerProfileResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerStatsDC>> GetPlayerProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetAchievements", ReplyAction="http://tempuri.org/IMainMenuService/GetAchievementsResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.AchievementDC[]> GetAchievements(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetAchievements", ReplyAction="http://tempuri.org/IMainMenuService/GetAchievementsResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.AchievementDC[]>> GetAchievementsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/IMainMenuService/GetGlobalLeaderboardResponse")]
        PapayagramsClient.PapayagramsService.LeaderboardStatsDC[] GetGlobalLeaderboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/IMainMenuService/GetGlobalLeaderboardResponse")]
        System.Threading.Tasks.Task<PapayagramsClient.PapayagramsService.LeaderboardStatsDC[]> GetGlobalLeaderboardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/ReportToServer", ReplyAction="http://tempuri.org/IMainMenuService/ReportToServerResponse")]
        int ReportToServer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainMenuService/ReportToServer", ReplyAction="http://tempuri.org/IMainMenuService/ReportToServerResponse")]
        System.Threading.Tasks.Task<int> ReportToServerAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainMenuServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMainMenuService/ReceiveGameInvitation")]
        void ReceiveGameInvitation(PapayagramsClient.PapayagramsService.GameInvitationDC invitation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainMenuServiceChannel : PapayagramsClient.PapayagramsService.IMainMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainMenuServiceClient : System.ServiceModel.DuplexClientBase<PapayagramsClient.PapayagramsService.IMainMenuService>, PapayagramsClient.PapayagramsService.IMainMenuService {
        
        public MainMenuServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MainMenuServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MainMenuServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainMenuServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainMenuServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.FriendDC[]> GetAllRelationships(string username) {
            return base.Channel.GetAllRelationships(username);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.FriendDC[]>> GetAllRelationshipsAsync(string username) {
            return base.Channel.GetAllRelationshipsAsync(username);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC> SearchNoFriendPlayer(string searcherUsername, string searchedUsername) {
            return base.Channel.SearchNoFriendPlayer(searcherUsername, searchedUsername);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerDC>> SearchNoFriendPlayerAsync(string searcherUsername, string searchedUsername) {
            return base.Channel.SearchNoFriendPlayerAsync(searcherUsername, searchedUsername);
        }
        
        public int SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<int> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public int RespondFriendRequest(string respondentUsername, string requesterUsername, bool response) {
            return base.Channel.RespondFriendRequest(respondentUsername, requesterUsername, response);
        }
        
        public System.Threading.Tasks.Task<int> RespondFriendRequestAsync(string respondentUsername, string requesterUsername, bool response) {
            return base.Channel.RespondFriendRequestAsync(respondentUsername, requesterUsername, response);
        }
        
        public int RemoveFriend(string username, string friendUsername) {
            return base.Channel.RemoveFriend(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<int> RemoveFriendAsync(string username, string friendUsername) {
            return base.Channel.RemoveFriendAsync(username, friendUsername);
        }
        
        public int BlockPlayer(string username, string friendUsername) {
            return base.Channel.BlockPlayer(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<int> BlockPlayerAsync(string username, string friendUsername) {
            return base.Channel.BlockPlayerAsync(username, friendUsername);
        }
        
        public int UnblockPlayer(string username, string friendUsername) {
            return base.Channel.UnblockPlayer(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<int> UnblockPlayerAsync(string username, string friendUsername) {
            return base.Channel.UnblockPlayerAsync(username, friendUsername);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerStatsDC> GetPlayerProfile(string username) {
            return base.Channel.GetPlayerProfile(username);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.PlayerStatsDC>> GetPlayerProfileAsync(string username) {
            return base.Channel.GetPlayerProfileAsync(username);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.AchievementDC[]> GetAchievements(string username) {
            return base.Channel.GetAchievements(username);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.AchievementDC[]>> GetAchievementsAsync(string username) {
            return base.Channel.GetAchievementsAsync(username);
        }
        
        public PapayagramsClient.PapayagramsService.LeaderboardStatsDC[] GetGlobalLeaderboard() {
            return base.Channel.GetGlobalLeaderboard();
        }
        
        public System.Threading.Tasks.Task<PapayagramsClient.PapayagramsService.LeaderboardStatsDC[]> GetGlobalLeaderboardAsync() {
            return base.Channel.GetGlobalLeaderboardAsync();
        }
        
        public int ReportToServer(string username) {
            return base.Channel.ReportToServer(username);
        }
        
        public System.Threading.Tasks.Task<int> ReportToServerAsync(string username) {
            return base.Channel.ReportToServerAsync(username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.IApplicationSettingsService")]
    public interface IApplicationSettingsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdateAplicationSettings", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdateAplicationSettingsResponse")]
        int UpdateAplicationSettings(string username, PapayagramsClient.PapayagramsService.ApplicationSettingsDC updatedConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdateAplicationSettings", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdateAplicationSettingsResponse")]
        System.Threading.Tasks.Task<int> UpdateAplicationSettingsAsync(string username, PapayagramsClient.PapayagramsService.ApplicationSettingsDC updatedConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/GetApplicationSettings", ReplyAction="http://tempuri.org/IApplicationSettingsService/GetApplicationSettingsResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.ApplicationSettingsDC> GetApplicationSettings(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/GetApplicationSettings", ReplyAction="http://tempuri.org/IApplicationSettingsService/GetApplicationSettingsResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.ApplicationSettingsDC>> GetApplicationSettingsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdateProfileIcon", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdateProfileIconResponse")]
        int UpdateProfileIcon(string username, int profileIcon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdateProfileIcon", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdateProfileIconResponse")]
        System.Threading.Tasks.Task<int> UpdateProfileIconAsync(string username, int profileIcon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdatePassword", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdatePasswordResponse")]
        int UpdatePassword(string username, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettingsService/UpdatePassword", ReplyAction="http://tempuri.org/IApplicationSettingsService/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<int> UpdatePasswordAsync(string username, string currentPassword, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationSettingsServiceChannel : PapayagramsClient.PapayagramsService.IApplicationSettingsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationSettingsServiceClient : System.ServiceModel.ClientBase<PapayagramsClient.PapayagramsService.IApplicationSettingsService>, PapayagramsClient.PapayagramsService.IApplicationSettingsService {
        
        public ApplicationSettingsServiceClient() {
        }
        
        public ApplicationSettingsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationSettingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationSettingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationSettingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UpdateAplicationSettings(string username, PapayagramsClient.PapayagramsService.ApplicationSettingsDC updatedConfiguration) {
            return base.Channel.UpdateAplicationSettings(username, updatedConfiguration);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAplicationSettingsAsync(string username, PapayagramsClient.PapayagramsService.ApplicationSettingsDC updatedConfiguration) {
            return base.Channel.UpdateAplicationSettingsAsync(username, updatedConfiguration);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.ApplicationSettingsDC> GetApplicationSettings(string username) {
            return base.Channel.GetApplicationSettings(username);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.ApplicationSettingsDC>> GetApplicationSettingsAsync(string username) {
            return base.Channel.GetApplicationSettingsAsync(username);
        }
        
        public int UpdateProfileIcon(string username, int profileIcon) {
            return base.Channel.UpdateProfileIcon(username, profileIcon);
        }
        
        public System.Threading.Tasks.Task<int> UpdateProfileIconAsync(string username, int profileIcon) {
            return base.Channel.UpdateProfileIconAsync(username, profileIcon);
        }
        
        public int UpdatePassword(string username, string currentPassword, string newPassword) {
            return base.Channel.UpdatePassword(username, currentPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePasswordAsync(string username, string currentPassword, string newPassword) {
            return base.Channel.UpdatePasswordAsync(username, currentPassword, newPassword);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.IPregameService", CallbackContract=typeof(PapayagramsClient.PapayagramsService.IPregameServiceCallback))]
    public interface IPregameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/CreateGame", ReplyAction="http://tempuri.org/IPregameService/CreateGameResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC> CreateGame(string username, PapayagramsClient.PapayagramsService.GameConfigurationDC gameConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/CreateGame", ReplyAction="http://tempuri.org/IPregameService/CreateGameResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC>> CreateGameAsync(string username, PapayagramsClient.PapayagramsService.GameConfigurationDC gameConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/JoinGame", ReplyAction="http://tempuri.org/IPregameService/JoinGameResponse")]
        System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC> JoinGame(string username, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/JoinGame", ReplyAction="http://tempuri.org/IPregameService/JoinGameResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC>> JoinGameAsync(string username, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/LeaveLobby")]
        void LeaveLobby(string username, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/LeaveLobby")]
        System.Threading.Tasks.Task LeaveLobbyAsync(string username, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/SendMessage")]
        void SendMessage(PapayagramsClient.PapayagramsService.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(PapayagramsClient.PapayagramsService.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/StartGame", ReplyAction="http://tempuri.org/IPregameService/StartGameResponse")]
        void StartGame(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/StartGame", ReplyAction="http://tempuri.org/IPregameService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/InviteFriend")]
        void InviteFriend(string username, string invitedFriend, string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/InviteFriend")]
        System.Threading.Tasks.Task InviteFriendAsync(string username, string invitedFriend, string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/ReturnToLobby", ReplyAction="http://tempuri.org/IPregameService/ReturnToLobbyResponse")]
        void ReturnToLobby(string gameRoomCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPregameService/ReturnToLobby", ReplyAction="http://tempuri.org/IPregameService/ReturnToLobbyResponse")]
        System.Threading.Tasks.Task ReturnToLobbyAsync(string gameRoomCode, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPregameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/ReceiveMessage")]
        void ReceiveMessage(PapayagramsClient.PapayagramsService.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/CarryInsideGame")]
        void CarryInsideGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPregameService/RefreshLobby")]
        void RefreshLobby(PapayagramsClient.PapayagramsService.GameRoomDC gameRoom);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPregameServiceChannel : PapayagramsClient.PapayagramsService.IPregameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PregameServiceClient : System.ServiceModel.DuplexClientBase<PapayagramsClient.PapayagramsService.IPregameService>, PapayagramsClient.PapayagramsService.IPregameService {
        
        public PregameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PregameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PregameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PregameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PregameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC> CreateGame(string username, PapayagramsClient.PapayagramsService.GameConfigurationDC gameConfiguration) {
            return base.Channel.CreateGame(username, gameConfiguration);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC>> CreateGameAsync(string username, PapayagramsClient.PapayagramsService.GameConfigurationDC gameConfiguration) {
            return base.Channel.CreateGameAsync(username, gameConfiguration);
        }
        
        public System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC> JoinGame(string username, string roomCode) {
            return base.Channel.JoinGame(username, roomCode);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, PapayagramsClient.PapayagramsService.GameRoomDC>> JoinGameAsync(string username, string roomCode) {
            return base.Channel.JoinGameAsync(username, roomCode);
        }
        
        public void LeaveLobby(string username, string roomCode) {
            base.Channel.LeaveLobby(username, roomCode);
        }
        
        public System.Threading.Tasks.Task LeaveLobbyAsync(string username, string roomCode) {
            return base.Channel.LeaveLobbyAsync(username, roomCode);
        }
        
        public void SendMessage(PapayagramsClient.PapayagramsService.Message message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(PapayagramsClient.PapayagramsService.Message message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public void StartGame(string roomCode) {
            base.Channel.StartGame(roomCode);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string roomCode) {
            return base.Channel.StartGameAsync(roomCode);
        }
        
        public void InviteFriend(string username, string invitedFriend, string gameRoomCode) {
            base.Channel.InviteFriend(username, invitedFriend, gameRoomCode);
        }
        
        public System.Threading.Tasks.Task InviteFriendAsync(string username, string invitedFriend, string gameRoomCode) {
            return base.Channel.InviteFriendAsync(username, invitedFriend, gameRoomCode);
        }
        
        public void ReturnToLobby(string gameRoomCode, string username) {
            base.Channel.ReturnToLobby(gameRoomCode, username);
        }
        
        public System.Threading.Tasks.Task ReturnToLobbyAsync(string gameRoomCode, string username) {
            return base.Channel.ReturnToLobbyAsync(gameRoomCode, username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.IGameService", CallbackContract=typeof(PapayagramsClient.PapayagramsService.IGameServiceCallback))]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ReachServer")]
        void ReachServer(string username, string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ReachServer")]
        System.Threading.Tasks.Task ReachServerAsync(string username, string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/DumpPiece")]
        void DumpPiece(string gameRoomCode, string username, char piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/DumpPiece")]
        System.Threading.Tasks.Task DumpPieceAsync(string gameRoomCode, string username, char piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/TakeSeed")]
        void TakeSeed(string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/TakeSeed")]
        System.Threading.Tasks.Task TakeSeedAsync(string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ShoutPapaya")]
        void ShoutPapaya(string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ShoutPapaya")]
        System.Threading.Tasks.Task ShoutPapayaAsync(string gameRoomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/CalculateWinner")]
        void CalculateWinner(string gameRoomCode, string username, int score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/CalculateWinner")]
        System.Threading.Tasks.Task CalculateWinnerAsync(string gameRoomCode, string username, int score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/LeaveGame", ReplyAction="http://tempuri.org/IGameService/LeaveGameResponse")]
        void LeaveGame(string gameRoomCode, string username, bool gameEnded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/LeaveGame", ReplyAction="http://tempuri.org/IGameService/LeaveGameResponse")]
        System.Threading.Tasks.Task LeaveGameAsync(string gameRoomCode, string username, bool gameEnded);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/RefreshGameRoom")]
        void RefreshGameRoom(int piecesNumber, PapayagramsClient.PapayagramsService.PlayerDC[] connectedPlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/RefreshTimer")]
        void RefreshTimer(int remainingMinutes);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/AddSeedsToHand")]
        void AddSeedsToHand(char[] initalPieces);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/NotifyEndOfGame")]
        void NotifyEndOfGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/EndGame")]
        void EndGame(string winnerUsername, int score);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : PapayagramsClient.PapayagramsService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<PapayagramsClient.PapayagramsService.IGameService>, PapayagramsClient.PapayagramsService.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ReachServer(string username, string gameRoomCode) {
            base.Channel.ReachServer(username, gameRoomCode);
        }
        
        public System.Threading.Tasks.Task ReachServerAsync(string username, string gameRoomCode) {
            return base.Channel.ReachServerAsync(username, gameRoomCode);
        }
        
        public void DumpPiece(string gameRoomCode, string username, char piece) {
            base.Channel.DumpPiece(gameRoomCode, username, piece);
        }
        
        public System.Threading.Tasks.Task DumpPieceAsync(string gameRoomCode, string username, char piece) {
            return base.Channel.DumpPieceAsync(gameRoomCode, username, piece);
        }
        
        public void TakeSeed(string gameRoomCode) {
            base.Channel.TakeSeed(gameRoomCode);
        }
        
        public System.Threading.Tasks.Task TakeSeedAsync(string gameRoomCode) {
            return base.Channel.TakeSeedAsync(gameRoomCode);
        }
        
        public void ShoutPapaya(string gameRoomCode) {
            base.Channel.ShoutPapaya(gameRoomCode);
        }
        
        public System.Threading.Tasks.Task ShoutPapayaAsync(string gameRoomCode) {
            return base.Channel.ShoutPapayaAsync(gameRoomCode);
        }
        
        public void CalculateWinner(string gameRoomCode, string username, int score) {
            base.Channel.CalculateWinner(gameRoomCode, username, score);
        }
        
        public System.Threading.Tasks.Task CalculateWinnerAsync(string gameRoomCode, string username, int score) {
            return base.Channel.CalculateWinnerAsync(gameRoomCode, username, score);
        }
        
        public void LeaveGame(string gameRoomCode, string username, bool gameEnded) {
            base.Channel.LeaveGame(gameRoomCode, username, gameEnded);
        }
        
        public System.Threading.Tasks.Task LeaveGameAsync(string gameRoomCode, string username, bool gameEnded) {
            return base.Channel.LeaveGameAsync(gameRoomCode, username, gameEnded);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PapayagramsService.IGameCodeVerificationService")]
    public interface IGameCodeVerificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameCodeVerificationService/VerifyGameRoom", ReplyAction="http://tempuri.org/IGameCodeVerificationService/VerifyGameRoomResponse")]
        bool VerifyGameRoom(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameCodeVerificationService/VerifyGameRoom", ReplyAction="http://tempuri.org/IGameCodeVerificationService/VerifyGameRoomResponse")]
        System.Threading.Tasks.Task<bool> VerifyGameRoomAsync(string gameCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameCodeVerificationServiceChannel : PapayagramsClient.PapayagramsService.IGameCodeVerificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameCodeVerificationServiceClient : System.ServiceModel.ClientBase<PapayagramsClient.PapayagramsService.IGameCodeVerificationService>, PapayagramsClient.PapayagramsService.IGameCodeVerificationService {
        
        public GameCodeVerificationServiceClient() {
        }
        
        public GameCodeVerificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameCodeVerificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameCodeVerificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameCodeVerificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerifyGameRoom(string gameCode) {
            return base.Channel.VerifyGameRoom(gameCode);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyGameRoomAsync(string gameCode) {
            return base.Channel.VerifyGameRoomAsync(gameCode);
        }
    }
}
